### ISSUE TITLE
dolni menu neni responzivni

### ISSUE THREAD

**Issue by Alzpeta** [Alzpeta/CZU-frontend#13]
neb jsem tam narvala moc textu, tak se to tak jako hnusne rozhazuje.

**Comment by Merchans** [comment]
neni no :/ pokúsil som sa to upraviť tým že pod 800px sa vycentruje to menu, je to čosi lepšie...

**Comment by Alzpeta** [comment]
jo tak to je asi jedno. mně už je to vlastně celý jedno :D jsem naštvaná! ten projekt se mi nelíbí. je to nudný
