### ISSUE TITLE
BEM pojmenovani

### ISSUE THREAD

**Issue by Alzpeta** [Alzpeta/CZU-frontend#15]
alzbeta z te jmene konvence udelala bordel, takze pokud ma nekdo s ocd s tim problem, je mozne to opravit

**Comment by Merchans** [comment]
Pozrel som si tvoje class ako sú spravené a BEM tam neni určite potrebný, je to celkom intuitívne

**Comment by Alzpeta** [comment]
přesně tak! anarchie
